export enum TypeSite {
  SIEGE_SOCIAL = 'SIEGE_SOCIAL',
  BUREAU_REGIONAL = 'BUREAU_REGIONAL',
  CENTRE_OPERATIONNEL = 'CENTRE_OPERATIONNEL',
  DATACENTER = 'DATACENTER',
  SITE_CLIENT = 'SITE_CLIENT',
  FORMATION = 'FORMATION'
}